# Generated by Django 5.0.8 on 2026-05-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('UTILITY_BILL', 'Utility Bill'), ('BANK_STATEMENT', 'Bank Statement'), ('SALARY_SLIP', 'Salary Slip'), ('PROPERTY_DOC', 'Property Document'), ('SELFIE', 'Selfie')], max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='kyc_docs/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEFICIENT', 'Deficient')], default='UPLOADED', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('deficiency_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
        ),
    ]
