# Generated by Django 5.0.8 on 2026-05-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('IDENTITY', 'Identity'), ('ADDRESS', 'Address'), ('FACE_MATCH', 'Face Match'), ('LIVENESS', 'Liveness'), ('FIELD', 'Field'), ('VIDEO_KYC', 'Video KYC')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REVIEW', 'Review Required')], default='PENDING', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='customers.customer')),
            ],
        ),
    ]
