# Generated by Django 5.0.8 on 2026-05-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aml_score', models.IntegerField(default=0)),
                ('fraud_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('category', models.CharField(default='LOW', max_length=10)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(max_length=50)),
                ('matched_name', models.CharField(max_length=160)),
                ('confidence', models.FloatField(default=0)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_hits', to='customers.customer')),
            ],
        ),
    ]
